# Generated by Django 4.2.21 on 2025-05-18 18:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone number in international format (e.g., +233123456789).', max_length=128, null=True, region=None, unique=True),
        ),
    ]
