# Generated by Django 4.2.21 on 2025-05-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_remove_investor_name_investor_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='funds_available',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
