# Generated by Django 4.2.21 on 2025-05-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_alter_investor_funds_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='id_document',
            field=models.FileField(blank=True, help_text="Upload the investor's identification document (e.g., passport, ID card).", null=True, upload_to='investor_docs/'),
        ),
        migrations.AddField(
            model_name='investor',
            name='investment_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', help_text='Period over which earnings are paid.', max_length=20),
        ),
    ]
