# Generated by Django 4.2.21 on 2025-05-17 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_investor_id_document_investor_investment_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='last_profit_calculation',
            field=models.DateTimeField(blank=True, help_text='Date and time of the last profit calculation.', null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='profit_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total profit earned by the investor.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investment_period',
            field=models.IntegerField(help_text='Investment period in months (minimum 3 months for one quarter).', validators=[django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='investortransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Initial Deposit'), ('topup', 'Top-Up'), ('withdrawal', 'Withdrawal'), ('return', 'Return Payment'), ('profit', 'Profit')], max_length=20),
        ),
    ]
