# Generated by Django 4.2.21 on 2025-05-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0005_investor_last_profit_calculation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='profit_paid',
            field=models.BooleanField(default=False, help_text='Indicates whether the profit has been paid to the investor.'),
        ),
        migrations.AddField(
            model_name='investor',
            name='profit_paid_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the profit was paid.', null=True),
        ),
    ]
