# Generated by Django 4.2.21 on 2025-05-18 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0006_investor_profit_paid_investor_profit_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the investor was added to the system.'),
        ),
    ]
