# Generated by Django 4.2.21 on 2025-05-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20250515_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='original_term_months',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
