# Generated by Django 4.2.21 on 2025-05-18 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loan_status'),
        ('repayments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('due', 'Due'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='due', max_length=20)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedules', to='loans.loan')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
