# Generated by Django 4.2.21 on 2025-05-11 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrowers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='credit_score',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='name',
        ),
        migrations.AddField(
            model_name='borrower',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='guarantor_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='guarantor_id_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='guarantor_id_file',
            field=models.FileField(blank=True, null=True, upload_to='borrowers/guarantor_id_docs/'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='guarantor_id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='guarantor_id_type',
            field=models.CharField(blank=True, choices=[('nid', 'National ID Card'), ('pp', 'Passport'), ('voter', 'Voter ID')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='guarantor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='guarantor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='guarantor_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='id_doc_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='id_doc_file',
            field=models.FileField(blank=True, null=True, upload_to='borrowers/id_docs/'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='id_doc_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='id_doc_type',
            field=models.CharField(blank=True, choices=[('nid', 'National ID Card'), ('pp', 'Passport'), ('voter', 'Voter ID')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='region',
            field=models.CharField(blank=True, choices=[('Greater Accra', 'Greater Accra'), ('Ashanti', 'Ashanti'), ('Northern', 'Northern'), ('Upper East', 'Upper East'), ('Upper West', 'Upper West'), ('Volta', 'Volta'), ('Eastern', 'Eastern'), ('Western', 'Western'), ('Central', 'Central'), ('Bono', 'Bono'), ('Bono East', 'Bono East'), ('Ahafo', 'Ahafo'), ('Savannah', 'Savannah'), ('North East', 'North East'), ('Oti', 'Oti'), ('Western North', 'Western North')], max_length=20, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='BorrowerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='borrowers/additional_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_docs', to='borrowers.borrower')),
            ],
        ),
    ]
