# Generated by Django 4.2.21 on 2025-05-11 21:04

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0002_remove_borrower_credit_score_remove_borrower_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='guarantor_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='guarantor_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='GH'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='GH'),
        ),
    ]
