# Generated by Django 4.2.21 on 2025-08-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowers", "0003_alter_borrower_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrower",
            name="guarantor_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="borrower",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
