"""
Django settings for loan_mgmt project.

Generated by 'django-admin startproject' using Django 4.2.21.
"""

from pathlib import Path
from celery.schedules import crontab

# ────────────────────────────────────────────────────────────────
# BASE DIR
# ────────────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent


# ────────────────────────────────────────────────────────────────
# SECURITY
# ────────────────────────────────────────────────────────────────
SECRET_KEY = 'django-insecure-mhd$g%dsrh^pjx=7884p2q6!!#nsyb585^d4bjr*8f+x5l5hxb'
DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# ────────────────────────────────────────────────────────────────
# APPLICATION DEFINITION
# ────────────────────────────────────────────────────────────────
INSTALLED_APPS = [
    # Django built-ins
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # Third-party
    'widget_tweaks',
    'phonenumber_field',
    'django_celery_beat',

    # Local
    'users',
    'borrowers',
    'investors',
    'loans',
    'repayments',
    'notifications',
    'exchange_rates',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'loan_mgmt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # global templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'loan_mgmt.wsgi.application'


# ────────────────────────────────────────────────────────────────
# DATABASE
# ────────────────────────────────────────────────────────────────
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ────────────────────────────────────────────────────────────────
# AUTH
# ────────────────────────────────────────────────────────────────
AUTH_USER_MODEL = 'users.User'
AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator' },
]

# Authentication Settings
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# ────────────────────────────────────────────────────────────────
# INTERNATIONALIZATION
# ────────────────────────────────────────────────────────────────
LANGUAGE_CODE = 'en-us'
TIME_ZONE     = 'Africa/Accra'
USE_I18N      = True
USE_TZ        = True


# ────────────────────────────────────────────────────────────────
# STATIC FILES (CSS, JS)
# ────────────────────────────────────────────────────────────────
STATIC_URL        = '/static/'
STATICFILES_DIRS  = [BASE_DIR / 'static']


# ────────────────────────────────────────────────────────────────
# MEDIA (uploads)
# ────────────────────────────────────────────────────────────────
MEDIA_URL   = '/media/'
MEDIA_ROOT  = BASE_DIR / 'media'


# ────────────────────────────────────────────────────────────────
# CELERY / REDIS
# ────────────────────────────────────────────────────────────────
# loan_mgmt/settings.py (update the CELERY_BEAT_SCHEDULE section)
CELERY_BROKER_URL     = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/1'
CELERY_BEAT_SCHEDULE = {
    'send-due-sms-every-morning': {
        'task': 'notifications.tasks.send_due_sms',
        'schedule': crontab(hour=8, minute=0),
        'args': (1,),
    },
    'calculate-investor-profits-daily': {
        'task': 'loan_mgmt.tasks.calculate_investor_profits',
        'schedule': crontab(hour=0, minute=0),  # Runs daily at midnight
    },
}


# ────────────────────────────────────────────────────────────────
# TWILIO (fill in your creds)
# ────────────────────────────────────────────────────────────────
TWILIO_ACCOUNT_SID = '<your_twilio_account_sid>'
TWILIO_AUTH_TOKEN  = '<your_twilio_auth_token>'
TWILIO_FROM_NUMBER = '+1XXXXXXXXXX'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# loan_mgmt/settings.py (add to the end)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_PORT = 25
EMAIL_USE_TLS = False
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
DEFAULT_FROM_EMAIL = 'LoanMgmt <no-reply@loanmgmt.com>'